### ISSUE TITLE
Cant build on cygwin because of zlib 1.2.8 dependency

### ISSUE THREAD

**Issue by absrnd** [part-cw/lambdanative#68]
I have installed Lambdanative on Cygwin and tring to build the example programs, and the build is failing when compiling zlib 1.2.8. However when I clone zlib it compiles ok. This is because there are updates to zlib in the head revision that allow it to compile under Cygwin.

How can I force LN to download the head revision or use the installed library?

Or would it be possible to update the revision of zlib that LN is downloading?

Thanks.

## Build fails using zlib 1.2.8
```
$ ./configure Calculator
==> configured to build Calculator for win32 in normal mode
 == using source in /cygdrive/c/Users/stuartm/apps/lambdanative/apps/Calculator

stuartm@FSS-FUJI-DT022 ~/apps/lambdanative
$ make
=== using profile your profile name here [/cygdrive/c/Users/stuartm/apps/lambdanative/PROFILE]..
=== configured to build Calculator version 1.0 for win32 on win32 in normal mode
lambdanative: 1dda742
==> checking for required tools..
** WARNING: xelatex rendering needs ps2eps, convert, gswin32, and pdf2ps/pdftops, some of which are missing.
 ** Using GD to render strings
==> checking for required libraries..
==> checking for lambdanative tools..
 => building lambdanative tool pngtool..
lambdanative: 1dda742
==> creating libraries needed for pngtool..
 => libz..
 => extracting /cygdrive/c/Users/stuartm/.cache/lambdanative/packages/zlib-1.2.8.tar.gz..
 => compiling source..
  CHOST=i686-pc-cygwin   PKG_CONFIG_PATH=/cygdrive/c/Users/stuartm/.cache/lambdanative/win32/lib/pkgconfig   PATH="/cygdrive/c/Users/stuartm/.cache/lambdanative/win32/bin:/usr/local/bin:/usr/bin:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files (x86)/Intel/iCLS Client:/cygdrive/c/Program Files/Intel/iCLS Client:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files/TortoiseSVN/bin:/cygdrive/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/cygdrive/c/Program Files (x86)/NVIDIA Corporation/Cg/bin:/cygdrive/c/Program Files (x86)/NVIDIA Corporation/Cg/bin.x64:/cygdrive/c/Users/stuartm/AppData/Local/Box/Box Edit:/usr/lib/lapack:/usr/openwin/bin:/usr/local/Gambit-C/bin:/usr/x86_64-w64-mingw32/sys-root/mingw/bin:/usr/x86_64-w64-mingw32/bin:/cygdrive/c/Users/stuartm/AppData/Local/Android/android-sdk/platform-tools"   LDFLAGS=-L/cygdrive/c/Users/stuartm/.cache/lambdanative/win32/lib   LD_LIBRARY_PATH=/cygdrive/c/Users/stuartm/.cache/lambdanative/win32/lib   CPPFLAGS=-I/cygdrive/c/Users/stuartm/.cache/lambdanative/win32/include   CC="gcc  -DWIN32 -DMINGW32 -DWINVER=0x0501 -I/cygdrive/c/Users/stuartm/.cache/lambdanative/win32/include -L/cygdrive/c/Users/stuartm/.cache/lambdanative/win32/lib -I/cygdrive/c/Users/stuartm/.cache/lambdanative/win32/include -L/cygdrive/c/Users/stuartm/.cache/lambdanative/win32/lib"   AR=ar   RANLIB=ranlib   make
make[1]: Entering directory '/cygdrive/c/Users/stuartm/.lambdanative/tmp_install/zlib-1.2.8'
gcc  -O3 -Wall -c -o adler32.o adler32.c
gcc  -O3 -Wall -c -o compress.o compress.c
gcc  -O3 -Wall -c -o crc32.o crc32.c
gcc  -O3 -Wall -c -o deflate.o deflate.c
gcc  -O3 -Wall -c -o gzclose.o gzclose.c
gcc  -O3 -Wall -c -o gzlib.o gzlib.c
gzlib.c: In function ‘gz_open’:
gzlib.c:256:9: warning: implicit declaration of function ‘lseek’ [-Wimplicit-function-declaration]
         state->start = LSEEK(state->fd, 0, SEEK_CUR);
         ^
gcc  -O3 -Wall -c -o gzread.o gzread.c
gzread.c: In function ‘gz_load’:
gzread.c:30:9: warning: implicit declaration of function ‘read’ [-Wimplicit-function-declaration]
         ret = read(state->fd, buf + *have, len - *have);
         ^
gzread.c: In function ‘gzclose_r’:
gzread.c:591:5: warning: implicit declaration of function ‘close’ [-Wimplicit-function-declaration]
     ret = close(state->fd);
     ^
gcc  -O3 -Wall -c -o gzwrite.o gzwrite.c
gzwrite.c: In function ‘gz_comp’:
gzwrite.c:84:9: warning: implicit declaration of function ‘write’ [-Wimplicit-function-declaration]
         got = write(state->fd, strm->next_in, strm->avail_in);
         ^
gzwrite.c: In function ‘gzclose_w’:
gzwrite.c:573:5: warning: implicit declaration of function ‘close’ [-Wimplicit-function-declaration]
     if (close(state->fd) == -1)
     ^
gcc  -O3 -Wall -c -o infback.o infback.c
gcc  -O3 -Wall -c -o inffast.o inffast.c
gcc  -O3 -Wall -c -o inflate.o inflate.c
gcc  -O3 -Wall -c -o inftrees.o inftrees.c
gcc  -O3 -Wall -c -o trees.o trees.c
gcc  -O3 -Wall -c -o uncompr.o uncompr.c
gcc  -O3 -Wall -c -o zutil.o zutil.c
ar rcs libz.a adler32.o compress.o crc32.o deflate.o gzclose.o gzlib.o gzread.o gzwrite.o infback.o inffast.o inflate.o inftrees.o trees.o uncompr.o zutil.o
windres --define GCC_WINDRES -o zlibrc.o win32/zlib1.rc
gcc -shared -Wl,--out-implib,libz.dll.a  \
-o zlib1.dll win32/zlib.def adler32.o compress.o crc32.o deflate.o gzclose.o gzlib.o gzread.o gzwrite.o infback.o inffast.o inflate.o inftrees.o trees.o uncompr.o zutil.o  zlibrc.o
Cannot export gzopen_w: symbol not defined
collect2: error: ld returned 1 exit status
Makefile:96: recipe for target 'zlib1.dll' failed
make[1]: *** [zlib1.dll] Error 1
make[1]: Leaving directory '/cygdrive/c/Users/stuartm/.lambdanative/tmp_install/zlib-1.2.8'
ERROR: failed with exit code 2
>> make failed
BUILD FAILED - configure with verbose option for more information
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
```

## However zlib builds from head revision

The issue(s) with zlib 1.2.8 have been resolved, and as can be seen below, the head revision of zlib now builds under cygwin.
```
$ git clone http://github.com/madler/zlib
Cloning into 'zlib'...
remote: Counting objects: 4355, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 4355 (delta 2), reused 0 (delta 0), pack-reused 4347
Receiving objects: 100% (4355/4355), 3.58 MiB | 281.00 KiB/s, done.
Resolving deltas: 100% (2586/2586), done.
Checking connectivity... done.

stuartm@FSS-FUJI-DT022 ~/.lambdanative/tmp_install
$ cd zlib

stuartm@FSS-FUJI-DT022 ~/.lambdanative/tmp_install/zlib
$ make
Please use ./configure first.  Thank you.

stuartm@FSS-FUJI-DT022 ~/.lambdanative/tmp_install/zlib
$ ./configure
Checking for gcc...
Checking for shared library support...
No shared library support.
Building static library libz.a version 1.2.8 with gcc.
Checking for off64_t... No.
Checking for fseeko... Yes.
Checking for strerror... Yes.
Checking for unistd.h... Yes.
Checking for stdarg.h... Yes.
Checking whether to use vs[n]printf() or s[n]printf()... using vs[n]printf().
Checking for vsnprintf() in stdio.h... Yes.
Checking for return value of vsnprintf()... Yes.
Checking for attribute(visibility) support... No.

stuartm@FSS-FUJI-DT022 ~/.lambdanative/tmp_install/zlib
$ make
gcc -O3  -I. -c -o example.o test/example.c
gcc -O3    -c -o adler32.o adler32.c
gcc -O3    -c -o crc32.o crc32.c
gcc -O3    -c -o deflate.o deflate.c
gcc -O3    -c -o infback.o infback.c
gcc -O3    -c -o inffast.o inffast.c
gcc -O3    -c -o inflate.o inflate.c
gcc -O3    -c -o inftrees.o inftrees.c
gcc -O3    -c -o trees.o trees.c
gcc -O3    -c -o zutil.o zutil.c
gcc -O3    -c -o compress.o compress.c
gcc -O3    -c -o uncompr.o uncompr.c
gcc -O3    -c -o gzclose.o gzclose.c
gcc -O3    -c -o gzlib.o gzlib.c
gcc -O3    -c -o gzread.o gzread.c
gcc -O3    -c -o gzwrite.o gzwrite.c
ar rc libz.a adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o zutil.o compress.o uncompr.o gzclose.o gzlib.o gzread.o gzwrite.o
gcc -O3  -o example.exe example.o -L. libz.a
gcc -O3  -I. -c -o minigzip.o test/minigzip.c
gcc -O3  -o minigzip.exe minigzip.o -L. libz.a

```

**Comment by clpetersen** [comment]
Thanks for spotting this, now fixed in commit 173a81e. To answer your question, libraries can be cloned from github simply by putting the github url in the libraries `make.sh` PKGURL, and have PKGHASH be the desired commit hash.

**Comment by mgorges** [comment]
I believe the git code and previous version are identical, so reopening this bug for further exploration. - @absrnd can you confirm if the problem still remains with the patch by @clpetersen ?

**Comment by clpetersen** [comment]
Actually, looking further into this, LambdaNative has never been tested against cygwin. The supported environment on windows so far is mingw. @absrnd, what is your cygwin setup.. 32bit or 64bit? And is libz the only problem you have with the build?

**Comment by clpetersen** [comment]
I was finally able to reproduce the libz problem with a fresh cygwin installation. This was indeed not fixed by the git code change, as noted by @mgorges. Commit fefa431 should fix the problem properly. With this change I'm able to compile and install DemoConsole in the cygwin environment without further issues.

**Comment by absrnd** [comment]
The DemoConsole example program builds and runs on Cygwin 32 for me now. MANY THANKS.

Calculator example is still failing to link (undefined opengl functions).. but suspect my cygwin environment might be to blame!

**Comment by clpetersen** [comment]
I just tried to build the Calculator in cygwin 32bit, and it stopped because of a missing ImageMagick dependency (convert). After installing ImageMagick the compilation completes and the app runs. Hope that might do the trick for you as well.
